#离谱 这个居然修复了
GET http://reader.sh.vip.qq.com/cgi-bin/common_async_cgi?g_tk=5381&plat=1&version=6.6.6&param=%7B%22key0%22%3A%7B%22param%22%3A%7B%22bid%22%3A13792605%7D%2C%22module%22%3A%22reader_comment_read_svr%22%2C%22method%22%3A%22GetReadAllEndPageMsg%22%7D%7D/api/item?id=99
Accept: application/json

###
