// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ClientInfo.proto

package HttpConn

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpConnSig struct {
	Uin                  *uint32                 `protobuf:"varint,1,req,name=Uin" json:"Uin,omitempty"`
	Tag2                 *uint32                 `protobuf:"varint,2,req,name=tag2" json:"tag2,omitempty"`
	Tag3                 *uint32                 `protobuf:"varint,3,req,name=tag3" json:"tag3,omitempty"`
	SubCmd               *uint32                 `protobuf:"varint,4,req,name=SubCmd" json:"SubCmd,omitempty"`
	ClientVer            *uint32                 `protobuf:"varint,5,req,name=ClientVer" json:"ClientVer,omitempty"`
	DwClientType         *uint32                 `protobuf:"varint,7,req,name=DwClientType" json:"DwClientType,omitempty"`
	DwPubNo              *uint32                 `protobuf:"varint,8,req,name=DwPubNo" json:"DwPubNo,omitempty"`
	ServiceId            *uint32                 `protobuf:"varint,17,req,name=ServiceId" json:"ServiceId,omitempty"`
	BufSigHttpConnToken  []byte                  `protobuf:"bytes,18,req,name=BufSigHttpConnToken" json:"BufSigHttpConnToken,omitempty"`
	Tag19                *uint32                 `protobuf:"varint,19,req,name=tag19" json:"tag19,omitempty"`
	Tag24                *uint32                 `protobuf:"varint,24,req,name=tag24" json:"tag24,omitempty"`
	Tag25                *HttpConnSigUnknowTag25 `protobuf:"bytes,25,req,name=tag25" json:"tag25,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *HttpConnSig) Reset()         { *m = HttpConnSig{} }
func (m *HttpConnSig) String() string { return proto.CompactTextString(m) }
func (*HttpConnSig) ProtoMessage()    {}
func (*HttpConnSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7464c5f64ed4ba, []int{0}
}
func (m *HttpConnSig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HttpConnSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HttpConnSig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HttpConnSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpConnSig.Merge(m, src)
}
func (m *HttpConnSig) XXX_Size() int {
	return m.Size()
}
func (m *HttpConnSig) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpConnSig.DiscardUnknown(m)
}

var xxx_messageInfo_HttpConnSig proto.InternalMessageInfo

func (m *HttpConnSig) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

func (m *HttpConnSig) GetTag2() uint32 {
	if m != nil && m.Tag2 != nil {
		return *m.Tag2
	}
	return 0
}

func (m *HttpConnSig) GetTag3() uint32 {
	if m != nil && m.Tag3 != nil {
		return *m.Tag3
	}
	return 0
}

func (m *HttpConnSig) GetSubCmd() uint32 {
	if m != nil && m.SubCmd != nil {
		return *m.SubCmd
	}
	return 0
}

func (m *HttpConnSig) GetClientVer() uint32 {
	if m != nil && m.ClientVer != nil {
		return *m.ClientVer
	}
	return 0
}

func (m *HttpConnSig) GetDwClientType() uint32 {
	if m != nil && m.DwClientType != nil {
		return *m.DwClientType
	}
	return 0
}

func (m *HttpConnSig) GetDwPubNo() uint32 {
	if m != nil && m.DwPubNo != nil {
		return *m.DwPubNo
	}
	return 0
}

func (m *HttpConnSig) GetServiceId() uint32 {
	if m != nil && m.ServiceId != nil {
		return *m.ServiceId
	}
	return 0
}

func (m *HttpConnSig) GetBufSigHttpConnToken() []byte {
	if m != nil {
		return m.BufSigHttpConnToken
	}
	return nil
}

func (m *HttpConnSig) GetTag19() uint32 {
	if m != nil && m.Tag19 != nil {
		return *m.Tag19
	}
	return 0
}

func (m *HttpConnSig) GetTag24() uint32 {
	if m != nil && m.Tag24 != nil {
		return *m.Tag24
	}
	return 0
}

func (m *HttpConnSig) GetTag25() *HttpConnSigUnknowTag25 {
	if m != nil {
		return m.Tag25
	}
	return nil
}

type HttpConnSigUnknowTag25 struct {
	Tag1                 *uint32  `protobuf:"varint,1,req,name=tag1" json:"tag1,omitempty"`
	Tag2                 *uint32  `protobuf:"varint,2,req,name=tag2" json:"tag2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpConnSigUnknowTag25) Reset()         { *m = HttpConnSigUnknowTag25{} }
func (m *HttpConnSigUnknowTag25) String() string { return proto.CompactTextString(m) }
func (*HttpConnSigUnknowTag25) ProtoMessage()    {}
func (*HttpConnSigUnknowTag25) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7464c5f64ed4ba, []int{0, 0}
}
func (m *HttpConnSigUnknowTag25) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HttpConnSigUnknowTag25) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HttpConnSigUnknowTag25.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HttpConnSigUnknowTag25) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpConnSigUnknowTag25.Merge(m, src)
}
func (m *HttpConnSigUnknowTag25) XXX_Size() int {
	return m.Size()
}
func (m *HttpConnSigUnknowTag25) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpConnSigUnknowTag25.DiscardUnknown(m)
}

var xxx_messageInfo_HttpConnSigUnknowTag25 proto.InternalMessageInfo

func (m *HttpConnSigUnknowTag25) GetTag1() uint32 {
	if m != nil && m.Tag1 != nil {
		return *m.Tag1
	}
	return 0
}

func (m *HttpConnSigUnknowTag25) GetTag2() uint32 {
	if m != nil && m.Tag2 != nil {
		return *m.Tag2
	}
	return 0
}

func init() {
	proto.RegisterType((*HttpConnSig)(nil), "HttpConn.HttpConnSig")
	proto.RegisterType((*HttpConnSigUnknowTag25)(nil), "HttpConn.HttpConnSig.unknowTag25")
}

func init() { proto.RegisterFile("ClientInfo.proto", fileDescriptor_8a7464c5f64ed4ba) }

var fileDescriptor_8a7464c5f64ed4ba = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x70, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xf1, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xf0, 0x28,
	0x29, 0x29, 0x70, 0xce, 0xcf, 0xcb, 0x53, 0x5a, 0xce, 0xcc, 0xc5, 0x0d, 0xe3, 0x04, 0x67, 0xa6,
	0x0b, 0x09, 0x70, 0x31, 0x87, 0x66, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x06, 0x81, 0x98,
	0x42, 0x42, 0x5c, 0x2c, 0x25, 0x89, 0xe9, 0x46, 0x12, 0x4c, 0x60, 0x21, 0x30, 0x1b, 0x2a, 0x66,
	0x2c, 0xc1, 0x0c, 0x17, 0x33, 0x16, 0x12, 0xe3, 0x62, 0x0b, 0x2e, 0x4d, 0x72, 0xce, 0x4d, 0x91,
	0x60, 0x01, 0x8b, 0x42, 0x79, 0x42, 0x32, 0x5c, 0x9c, 0x10, 0xfb, 0xc3, 0x52, 0x8b, 0x24, 0x58,
	0xc1, 0x52, 0x08, 0x01, 0x21, 0x25, 0x2e, 0x1e, 0x97, 0x72, 0x08, 0x37, 0xa4, 0xb2, 0x20, 0x55,
	0x82, 0x1d, 0xac, 0x00, 0x45, 0x4c, 0x48, 0x82, 0x8b, 0xdd, 0xa5, 0x3c, 0xa0, 0x34, 0xc9, 0x2f,
	0x5f, 0x82, 0x03, 0x2c, 0x0d, 0xe3, 0x82, 0xcc, 0x0e, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xf5,
	0x4c, 0x91, 0x10, 0x84, 0x98, 0x0d, 0x17, 0x10, 0x32, 0xe0, 0x12, 0x76, 0x2a, 0x4d, 0x0b, 0xce,
	0x4c, 0x87, 0x79, 0x30, 0x24, 0x3f, 0x3b, 0x35, 0x4f, 0x42, 0x48, 0x81, 0x49, 0x83, 0x27, 0x08,
	0x9b, 0x94, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x62, 0xba, 0xa1, 0xa5, 0x84, 0x30, 0xd8, 0x2c, 0x08,
	0x07, 0x2a, 0x6a, 0x64, 0x22, 0x21, 0x01, 0x17, 0x35, 0x32, 0x11, 0x32, 0x87, 0x88, 0x9a, 0x4a,
	0x48, 0x2a, 0x30, 0x69, 0x70, 0x1b, 0x29, 0xea, 0xc1, 0x8c, 0xd2, 0x43, 0x0a, 0x4f, 0xbd, 0xd2,
	0xbc, 0xec, 0xbc, 0xfc, 0xf2, 0x10, 0x90, 0x42, 0x88, 0x46, 0x53, 0x29, 0x53, 0x2e, 0x6e, 0x24,
	0x51, 0x68, 0x58, 0x1a, 0x42, 0x83, 0x1c, 0xcc, 0xc6, 0x16, 0xe6, 0x4e, 0x02, 0x27, 0x1e, 0xc9,
	0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x8c, 0xc7, 0x72, 0x0c, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc1, 0xc5, 0xd9, 0xb7, 0xd8, 0x01, 0x00, 0x00,
}

func (m *HttpConnSig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HttpConnSig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HttpConnSig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Tag25 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.Tag25.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClientInfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if m.Tag24 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Tag24))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if m.Tag19 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Tag19))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.BufSigHttpConnToken == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(m.BufSigHttpConnToken)
		copy(dAtA[i:], m.BufSigHttpConnToken)
		i = encodeVarintClientInfo(dAtA, i, uint64(len(m.BufSigHttpConnToken)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.ServiceId == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.ServiceId))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.DwPubNo == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.DwPubNo))
		i--
		dAtA[i] = 0x40
	}
	if m.DwClientType == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.DwClientType))
		i--
		dAtA[i] = 0x38
	}
	if m.ClientVer == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.ClientVer))
		i--
		dAtA[i] = 0x28
	}
	if m.SubCmd == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.SubCmd))
		i--
		dAtA[i] = 0x20
	}
	if m.Tag3 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Tag3))
		i--
		dAtA[i] = 0x18
	}
	if m.Tag2 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Tag2))
		i--
		dAtA[i] = 0x10
	}
	if m.Uin == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Uin))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HttpConnSigUnknowTag25) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HttpConnSigUnknowTag25) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HttpConnSigUnknowTag25) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Tag2 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Tag2))
		i--
		dAtA[i] = 0x10
	}
	if m.Tag1 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintClientInfo(dAtA, i, uint64(*m.Tag1))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintClientInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovClientInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HttpConnSig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Uin != nil {
		n += 1 + sovClientInfo(uint64(*m.Uin))
	}
	if m.Tag2 != nil {
		n += 1 + sovClientInfo(uint64(*m.Tag2))
	}
	if m.Tag3 != nil {
		n += 1 + sovClientInfo(uint64(*m.Tag3))
	}
	if m.SubCmd != nil {
		n += 1 + sovClientInfo(uint64(*m.SubCmd))
	}
	if m.ClientVer != nil {
		n += 1 + sovClientInfo(uint64(*m.ClientVer))
	}
	if m.DwClientType != nil {
		n += 1 + sovClientInfo(uint64(*m.DwClientType))
	}
	if m.DwPubNo != nil {
		n += 1 + sovClientInfo(uint64(*m.DwPubNo))
	}
	if m.ServiceId != nil {
		n += 2 + sovClientInfo(uint64(*m.ServiceId))
	}
	if m.BufSigHttpConnToken != nil {
		l = len(m.BufSigHttpConnToken)
		n += 2 + l + sovClientInfo(uint64(l))
	}
	if m.Tag19 != nil {
		n += 2 + sovClientInfo(uint64(*m.Tag19))
	}
	if m.Tag24 != nil {
		n += 2 + sovClientInfo(uint64(*m.Tag24))
	}
	if m.Tag25 != nil {
		l = m.Tag25.Size()
		n += 2 + l + sovClientInfo(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HttpConnSigUnknowTag25) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tag1 != nil {
		n += 1 + sovClientInfo(uint64(*m.Tag1))
	}
	if m.Tag2 != nil {
		n += 1 + sovClientInfo(uint64(*m.Tag2))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovClientInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClientInfo(x uint64) (n int) {
	return sovClientInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HttpConnSig) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HttpConnSig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HttpConnSig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uin", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Uin = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag2", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag2 = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag3", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag3 = &v
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubCmd", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SubCmd = &v
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientVer", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClientVer = &v
			hasFields[0] |= uint64(0x00000010)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DwClientType", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DwClientType = &v
			hasFields[0] |= uint64(0x00000020)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DwPubNo", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DwPubNo = &v
			hasFields[0] |= uint64(0x00000040)
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceId", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ServiceId = &v
			hasFields[0] |= uint64(0x00000080)
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufSigHttpConnToken", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BufSigHttpConnToken = append(m.BufSigHttpConnToken[:0], dAtA[iNdEx:postIndex]...)
			if m.BufSigHttpConnToken == nil {
				m.BufSigHttpConnToken = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000100)
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag19", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag19 = &v
			hasFields[0] |= uint64(0x00000200)
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag24", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag24 = &v
			hasFields[0] |= uint64(0x00000400)
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag25", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClientInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClientInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tag25 == nil {
				m.Tag25 = &HttpConnSigUnknowTag25{}
			}
			if err := m.Tag25.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000800)
		default:
			iNdEx = preIndex
			skippy, err := skipClientInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000200) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000400) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000800) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HttpConnSigUnknowTag25) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: unknowTag25: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: unknowTag25: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag1", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag1 = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag2", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag2 = &v
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipClientInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClientInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClientInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClientInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClientInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClientInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClientInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClientInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClientInfo = fmt.Errorf("proto: unexpected end of group")
)
