// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ReqBody.proto

package HttpConn

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqBody struct {
	HeadType             *uint32          `protobuf:"varint,1,req,name=headType" json:"headType,omitempty"`
	MsgHttpConnHead      *MsgHttpConnHead `protobuf:"bytes,4,req,name=msg_httpConn_head,json=msgHttpConnHead" json:"msg_httpConn_head,omitempty"`
	Skey                 *ReqBodyPSkeyBuf `protobuf:"bytes,6,req,name=Skey" json:"Skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqBody) Reset()         { *m = ReqBody{} }
func (m *ReqBody) String() string { return proto.CompactTextString(m) }
func (*ReqBody) ProtoMessage()    {}
func (*ReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9c5066afefd985d, []int{0}
}
func (m *ReqBody) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReqBody.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBody.Merge(m, src)
}
func (m *ReqBody) XXX_Size() int {
	return m.Size()
}
func (m *ReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBody proto.InternalMessageInfo

func (m *ReqBody) GetHeadType() uint32 {
	if m != nil && m.HeadType != nil {
		return *m.HeadType
	}
	return 0
}

func (m *ReqBody) GetMsgHttpConnHead() *MsgHttpConnHead {
	if m != nil {
		return m.MsgHttpConnHead
	}
	return nil
}

func (m *ReqBody) GetSkey() *ReqBodyPSkeyBuf {
	if m != nil {
		return m.Skey
	}
	return nil
}

type ReqBodyPSkeyBuf struct {
	Type                 *uint32  `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Sig                  *string  `protobuf:"bytes,2,req,name=sig" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBodyPSkeyBuf) Reset()         { *m = ReqBodyPSkeyBuf{} }
func (m *ReqBodyPSkeyBuf) String() string { return proto.CompactTextString(m) }
func (*ReqBodyPSkeyBuf) ProtoMessage()    {}
func (*ReqBodyPSkeyBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9c5066afefd985d, []int{0, 0}
}
func (m *ReqBodyPSkeyBuf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReqBodyPSkeyBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReqBodyPSkeyBuf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReqBodyPSkeyBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBodyPSkeyBuf.Merge(m, src)
}
func (m *ReqBodyPSkeyBuf) XXX_Size() int {
	return m.Size()
}
func (m *ReqBodyPSkeyBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBodyPSkeyBuf.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBodyPSkeyBuf proto.InternalMessageInfo

func (m *ReqBodyPSkeyBuf) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ReqBodyPSkeyBuf) GetSig() string {
	if m != nil && m.Sig != nil {
		return *m.Sig
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqBody)(nil), "HttpConn.ReqBody")
	proto.RegisterType((*ReqBodyPSkeyBuf)(nil), "HttpConn.ReqBody.pSkeyBuf")
}

func init() { proto.RegisterFile("ReqBody.proto", fileDescriptor_a9c5066afefd985d) }

var fileDescriptor_a9c5066afefd985d = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0d, 0x4a, 0x2d, 0x74,
	0xca, 0x4f, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xf0, 0x28, 0x29, 0x29, 0x70,
	0xce, 0xcf, 0xcb, 0x93, 0x12, 0xcb, 0x2d, 0x4e, 0x8f, 0xcf, 0x28, 0x29, 0x29, 0x48, 0xce, 0xcf,
	0xcb, 0xf3, 0x48, 0x4d, 0x4c, 0x81, 0xa8, 0x50, 0xba, 0xc0, 0xc8, 0xc5, 0x0e, 0xd5, 0x23, 0x24,
	0xc5, 0xc5, 0x91, 0x91, 0x9a, 0x98, 0x12, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1,
	0x1b, 0x04, 0xe7, 0x0b, 0xb9, 0x73, 0x09, 0xc2, 0x4c, 0x00, 0x99, 0x17, 0x0f, 0x92, 0x90, 0x60,
	0x51, 0x60, 0xd2, 0xe0, 0x36, 0x92, 0xd6, 0x83, 0xd9, 0xa2, 0x87, 0xa1, 0x24, 0x88, 0x3f, 0xb7,
	0x38, 0x1d, 0x26, 0x0d, 0xb2, 0x56, 0x48, 0x8f, 0x8b, 0x25, 0x38, 0x3b, 0xb5, 0x52, 0x82, 0x0d,
	0xac, 0x57, 0x0a, 0xa1, 0x17, 0xee, 0x72, 0x90, 0xb4, 0x53, 0x69, 0x5a, 0x10, 0x58, 0x9d, 0x94,
	0x01, 0x17, 0x07, 0x4c, 0x44, 0x48, 0x88, 0x8b, 0xa5, 0x04, 0xe1, 0x38, 0x30, 0x5b, 0x48, 0x80,
	0x8b, 0xb9, 0x38, 0x33, 0x5d, 0x82, 0x49, 0x81, 0x49, 0x83, 0x33, 0x08, 0xc4, 0x74, 0x12, 0x38,
	0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x67, 0x3c, 0x96, 0x63,
	0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xd5, 0x6f, 0x59, 0x16, 0x01, 0x00, 0x00,
}

func (m *ReqBody) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReqBody) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReqBody) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Skey == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.Skey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReqBody(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.MsgHttpConnHead == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.MsgHttpConnHead.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReqBody(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.HeadType == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintReqBody(dAtA, i, uint64(*m.HeadType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReqBodyPSkeyBuf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReqBodyPSkeyBuf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReqBodyPSkeyBuf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Sig == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(*m.Sig)
		copy(dAtA[i:], *m.Sig)
		i = encodeVarintReqBody(dAtA, i, uint64(len(*m.Sig)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintReqBody(dAtA, i, uint64(*m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintReqBody(dAtA []byte, offset int, v uint64) int {
	offset -= sovReqBody(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReqBody) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HeadType != nil {
		n += 1 + sovReqBody(uint64(*m.HeadType))
	}
	if m.MsgHttpConnHead != nil {
		l = m.MsgHttpConnHead.Size()
		n += 1 + l + sovReqBody(uint64(l))
	}
	if m.Skey != nil {
		l = m.Skey.Size()
		n += 1 + l + sovReqBody(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReqBodyPSkeyBuf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != nil {
		n += 1 + sovReqBody(uint64(*m.Type))
	}
	if m.Sig != nil {
		l = len(*m.Sig)
		n += 1 + l + sovReqBody(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovReqBody(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReqBody(x uint64) (n int) {
	return sovReqBody(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReqBody) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReqBody
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReqBody: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReqBody: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeadType", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HeadType = &v
			hasFields[0] |= uint64(0x00000001)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgHttpConnHead", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReqBody
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReqBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MsgHttpConnHead == nil {
				m.MsgHttpConnHead = &MsgHttpConnHead{}
			}
			if err := m.MsgHttpConnHead.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReqBody
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReqBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Skey == nil {
				m.Skey = &ReqBodyPSkeyBuf{}
			}
			if err := m.Skey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipReqBody(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReqBody
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReqBodyPSkeyBuf) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReqBody
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: pSkeyBuf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: pSkeyBuf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Type = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReqBody
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReqBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Sig = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipReqBody(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReqBody
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReqBody(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReqBody
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReqBody
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReqBody
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReqBody
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReqBody
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReqBody        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReqBody          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReqBody = fmt.Errorf("proto: unexpected end of group")
)
