// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cmd0x3f7.proto

package cmd0x3f7

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Targer struct {
	WCsCmdNo             *uint32  `protobuf:"varint,1,req,name=wCsCmdNo,def=1" json:"wCsCmdNo,omitempty"`
	GroupSub             *Info    `protobuf:"bytes,2,req,name=GroupSub" json:"GroupSub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Targer) Reset()         { *m = Targer{} }
func (m *Targer) String() string { return proto.CompactTextString(m) }
func (*Targer) ProtoMessage()    {}
func (*Targer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef7067a21f8f0368, []int{0}
}
func (m *Targer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Targer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Targer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Targer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Targer.Merge(m, src)
}
func (m *Targer) XXX_Size() int {
	return m.Size()
}
func (m *Targer) XXX_DiscardUnknown() {
	xxx_messageInfo_Targer.DiscardUnknown(m)
}

var xxx_messageInfo_Targer proto.InternalMessageInfo

const Default_Targer_WCsCmdNo uint32 = 1

func (m *Targer) GetWCsCmdNo() uint32 {
	if m != nil && m.WCsCmdNo != nil {
		return *m.WCsCmdNo
	}
	return Default_Targer_WCsCmdNo
}

func (m *Targer) GetGroupSub() *Info {
	if m != nil {
		return m.GroupSub
	}
	return nil
}

type Info struct {
	SubCmd               *uint32  `protobuf:"varint,19,opt,name=SubCmd" json:"SubCmd,omitempty"`
	GroupType            *uint32  `protobuf:"varint,51,req,name=GroupType" json:"GroupType,omitempty"`
	DwRequestId          *uint64  `protobuf:"varint,52,opt,name=dwRequestId,def=1" json:"dwRequestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef7067a21f8f0368, []int{1}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Info.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return m.Size()
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

const Default_Info_DwRequestId uint64 = 1

func (m *Info) GetSubCmd() uint32 {
	if m != nil && m.SubCmd != nil {
		return *m.SubCmd
	}
	return 0
}

func (m *Info) GetGroupType() uint32 {
	if m != nil && m.GroupType != nil {
		return *m.GroupType
	}
	return 0
}

func (m *Info) GetDwRequestId() uint64 {
	if m != nil && m.DwRequestId != nil {
		return *m.DwRequestId
	}
	return Default_Info_DwRequestId
}

//------------------------------------
type Msg struct {
	WCsCmdNo             *uint32  `protobuf:"varint,1,req,name=wCsCmdNo" json:"wCsCmdNo,omitempty"`
	Tag2                 *uint32  `protobuf:"varint,2,req,name=tag2" json:"tag2,omitempty"`
	GroupCode            *uint64  `protobuf:"varint,3,req,name=GroupCode" json:"GroupCode,omitempty"`
	Cs                   *Cs      `protobuf:"bytes,4,req,name=cs" json:"cs,omitempty"`
	Tag5                 *Tag5    `protobuf:"bytes,5,req,name=tag5" json:"tag5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef7067a21f8f0368, []int{2}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return m.Size()
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetWCsCmdNo() uint32 {
	if m != nil && m.WCsCmdNo != nil {
		return *m.WCsCmdNo
	}
	return 0
}

func (m *Msg) GetTag2() uint32 {
	if m != nil && m.Tag2 != nil {
		return *m.Tag2
	}
	return 0
}

func (m *Msg) GetGroupCode() uint64 {
	if m != nil && m.GroupCode != nil {
		return *m.GroupCode
	}
	return 0
}

func (m *Msg) GetCs() *Cs {
	if m != nil {
		return m.Cs
	}
	return nil
}

func (m *Msg) GetTag5() *Tag5 {
	if m != nil {
		return m.Tag5
	}
	return nil
}

type Cs struct {
	MsgSeq               *uint32  `protobuf:"varint,1,req,name=MsgSeq" json:"MsgSeq,omitempty"`
	MsgRandom            *uint32  `protobuf:"varint,2,req,name=MsgRandom" json:"MsgRandom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cs) Reset()         { *m = Cs{} }
func (m *Cs) String() string { return proto.CompactTextString(m) }
func (*Cs) ProtoMessage()    {}
func (*Cs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef7067a21f8f0368, []int{3}
}
func (m *Cs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Cs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cs.Merge(m, src)
}
func (m *Cs) XXX_Size() int {
	return m.Size()
}
func (m *Cs) XXX_DiscardUnknown() {
	xxx_messageInfo_Cs.DiscardUnknown(m)
}

var xxx_messageInfo_Cs proto.InternalMessageInfo

func (m *Cs) GetMsgSeq() uint32 {
	if m != nil && m.MsgSeq != nil {
		return *m.MsgSeq
	}
	return 0
}

func (m *Cs) GetMsgRandom() uint32 {
	if m != nil && m.MsgRandom != nil {
		return *m.MsgRandom
	}
	return 0
}

type Tag5 struct {
	Tag1                 *uint32   `protobuf:"varint,1,req,name=tag1" json:"tag1,omitempty"`
	Tag2                 *Tag5Tag2 `protobuf:"bytes,2,req,name=tag2" json:"tag2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tag5) Reset()         { *m = Tag5{} }
func (m *Tag5) String() string { return proto.CompactTextString(m) }
func (*Tag5) ProtoMessage()    {}
func (*Tag5) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef7067a21f8f0368, []int{4}
}
func (m *Tag5) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tag5) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tag5.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tag5) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag5.Merge(m, src)
}
func (m *Tag5) XXX_Size() int {
	return m.Size()
}
func (m *Tag5) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag5.DiscardUnknown(m)
}

var xxx_messageInfo_Tag5 proto.InternalMessageInfo

func (m *Tag5) GetTag1() uint32 {
	if m != nil && m.Tag1 != nil {
		return *m.Tag1
	}
	return 0
}

func (m *Tag5) GetTag2() *Tag5Tag2 {
	if m != nil {
		return m.Tag2
	}
	return nil
}

type Tag5Tag2 struct {
	MsgSeq               *uint32  `protobuf:"varint,1,req,name=MsgSeq" json:"MsgSeq,omitempty"`
	Tag2                 *uint32  `protobuf:"varint,2,req,name=tag2" json:"tag2,omitempty"`
	Tag3                 *uint32  `protobuf:"varint,3,req,name=tag3" json:"tag3,omitempty"`
	Tag4                 *uint32  `protobuf:"varint,4,req,name=tag4" json:"tag4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag5Tag2) Reset()         { *m = Tag5Tag2{} }
func (m *Tag5Tag2) String() string { return proto.CompactTextString(m) }
func (*Tag5Tag2) ProtoMessage()    {}
func (*Tag5Tag2) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef7067a21f8f0368, []int{5}
}
func (m *Tag5Tag2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tag5Tag2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tag5Tag2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tag5Tag2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag5Tag2.Merge(m, src)
}
func (m *Tag5Tag2) XXX_Size() int {
	return m.Size()
}
func (m *Tag5Tag2) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag5Tag2.DiscardUnknown(m)
}

var xxx_messageInfo_Tag5Tag2 proto.InternalMessageInfo

func (m *Tag5Tag2) GetMsgSeq() uint32 {
	if m != nil && m.MsgSeq != nil {
		return *m.MsgSeq
	}
	return 0
}

func (m *Tag5Tag2) GetTag2() uint32 {
	if m != nil && m.Tag2 != nil {
		return *m.Tag2
	}
	return 0
}

func (m *Tag5Tag2) GetTag3() uint32 {
	if m != nil && m.Tag3 != nil {
		return *m.Tag3
	}
	return 0
}

func (m *Tag5Tag2) GetTag4() uint32 {
	if m != nil && m.Tag4 != nil {
		return *m.Tag4
	}
	return 0
}

func init() {
	proto.RegisterType((*Targer)(nil), "cmd0x3f7.targer")
	proto.RegisterType((*Info)(nil), "cmd0x3f7.Info")
	proto.RegisterType((*Msg)(nil), "cmd0x3f7.msg")
	proto.RegisterType((*Cs)(nil), "cmd0x3f7.Cs")
	proto.RegisterType((*Tag5)(nil), "cmd0x3f7.tag5")
	proto.RegisterType((*Tag5Tag2)(nil), "cmd0x3f7.tag5_tag2")
}

func init() { proto.RegisterFile("cmd0x3f7.proto", fileDescriptor_ef7067a21f8f0368) }

var fileDescriptor_ef7067a21f8f0368 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4f, 0xf2, 0x30,
	0x18, 0xc7, 0xdf, 0x8e, 0xbd, 0x04, 0x8a, 0x10, 0x53, 0x12, 0xd3, 0x18, 0x5c, 0x96, 0x7a, 0x70,
	0xf1, 0x40, 0x84, 0x41, 0x4c, 0x38, 0xda, 0x83, 0xe1, 0x80, 0x87, 0xce, 0x3b, 0x19, 0x74, 0xec,
	0x34, 0x0a, 0xeb, 0x16, 0xf4, 0x83, 0x98, 0xf8, 0x91, 0x3c, 0xfa, 0x11, 0x0c, 0x7e, 0x11, 0xd3,
	0xae, 0x6e, 0x48, 0xf4, 0xd6, 0xe7, 0xf7, 0x6c, 0xcf, 0xf3, 0xfb, 0x3f, 0xb0, 0xb3, 0x4c, 0xf8,
	0xcd, 0x93, 0xbf, 0xba, 0xed, 0x6f, 0x52, 0x91, 0x09, 0xd4, 0xf8, 0xae, 0x49, 0x00, 0xeb, 0x59,
	0x98, 0xc6, 0x51, 0x8a, 0x2e, 0x60, 0x63, 0x47, 0x25, 0x4d, 0xf8, 0x83, 0xc0, 0xc0, 0xb5, 0xbc,
	0xf6, 0x04, 0x0c, 0x58, 0x89, 0xd0, 0x35, 0x6c, 0xdc, 0xa7, 0x22, 0xdf, 0x04, 0xf9, 0x02, 0x5b,
	0xae, 0xe5, 0xb5, 0x86, 0x9d, 0x7e, 0x39, 0x75, 0xba, 0x5e, 0x09, 0x56, 0xf6, 0x49, 0x08, 0x6d,
	0x45, 0xd0, 0x19, 0xac, 0x07, 0xf9, 0x82, 0x26, 0x1c, 0x77, 0x5d, 0xe0, 0xb5, 0x99, 0xa9, 0x50,
	0x0f, 0x36, 0xf5, 0xb7, 0x8f, 0xcf, 0x9b, 0x08, 0xfb, 0x6a, 0x17, 0xab, 0x00, 0xba, 0x84, 0x2d,
	0xbe, 0x63, 0xd1, 0x36, 0x8f, 0x64, 0x36, 0xe5, 0x78, 0xe4, 0x02, 0xcf, 0x56, 0x2e, 0x87, 0x94,
	0xbc, 0x00, 0x58, 0x4b, 0x64, 0x8c, 0xce, 0x8f, 0xad, 0x0f, 0x94, 0x11, 0xb4, 0xb3, 0x30, 0x1e,
	0x6a, 0xdd, 0x36, 0xd3, 0xef, 0x72, 0x35, 0x15, 0x3c, 0xc2, 0x35, 0xd7, 0xf2, 0x6c, 0x56, 0x01,
	0xd4, 0x83, 0xd6, 0x52, 0x62, 0x5b, 0xc7, 0x3b, 0xa9, 0xe2, 0x51, 0xc9, 0xac, 0xa5, 0x44, 0x44,
	0xcf, 0x1b, 0xe3, 0xff, 0xc7, 0xf1, 0x15, 0xd5, 0xf3, 0xc7, 0x64, 0x02, 0x2d, 0x2a, 0x55, 0xf0,
	0x99, 0x8c, 0x83, 0x68, 0x6b, 0x9c, 0x4c, 0xa5, 0xb6, 0xcf, 0x64, 0xcc, 0xc2, 0x35, 0x17, 0x89,
	0xd1, 0xaa, 0x00, 0xa1, 0xc5, 0x7c, 0xe3, 0x3d, 0x30, 0xff, 0xea, 0x37, 0xba, 0x3a, 0xc8, 0xd2,
	0x1a, 0x76, 0x7f, 0xee, 0x9e, 0xab, 0x56, 0x11, 0x90, 0xcc, 0x61, 0xb3, 0x44, 0x7f, 0x7a, 0xfc,
	0x76, 0x99, 0x82, 0xf9, 0xfa, 0x28, 0x05, 0xf3, 0x0d, 0x1b, 0xe9, 0x8b, 0x14, 0x6c, 0x74, 0x77,
	0xfa, 0xb6, 0x77, 0xc0, 0xfb, 0xde, 0x01, 0x1f, 0x7b, 0x07, 0xbc, 0x7e, 0x3a, 0xff, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0x51, 0x69, 0x62, 0x5e, 0x02, 0x00, 0x00,
}

func (m *Targer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Targer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Targer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.GroupSub == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.GroupSub.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCmd0X3F7(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.WCsCmdNo == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.WCsCmdNo))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Info) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Info) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Info) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.DwRequestId != nil {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.DwRequestId))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xa0
	}
	if m.GroupType == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.GroupType))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x98
	}
	if m.SubCmd != nil {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.SubCmd))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	return len(dAtA) - i, nil
}

func (m *Msg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Msg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Msg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Tag5 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.Tag5.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCmd0X3F7(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Cs == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.Cs.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCmd0X3F7(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.GroupCode == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.GroupCode))
		i--
		dAtA[i] = 0x18
	}
	if m.Tag2 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.Tag2))
		i--
		dAtA[i] = 0x10
	}
	if m.WCsCmdNo == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.WCsCmdNo))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Cs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Cs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MsgRandom == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.MsgRandom))
		i--
		dAtA[i] = 0x10
	}
	if m.MsgSeq == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.MsgSeq))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Tag5) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tag5) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tag5) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Tag2 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		{
			size, err := m.Tag2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCmd0X3F7(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Tag1 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.Tag1))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Tag5Tag2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tag5Tag2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tag5Tag2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Tag4 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.Tag4))
		i--
		dAtA[i] = 0x20
	}
	if m.Tag3 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.Tag3))
		i--
		dAtA[i] = 0x18
	}
	if m.Tag2 == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.Tag2))
		i--
		dAtA[i] = 0x10
	}
	if m.MsgSeq == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintCmd0X3F7(dAtA, i, uint64(*m.MsgSeq))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCmd0X3F7(dAtA []byte, offset int, v uint64) int {
	offset -= sovCmd0X3F7(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Targer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WCsCmdNo != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.WCsCmdNo))
	}
	if m.GroupSub != nil {
		l = m.GroupSub.Size()
		n += 1 + l + sovCmd0X3F7(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Info) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubCmd != nil {
		n += 2 + sovCmd0X3F7(uint64(*m.SubCmd))
	}
	if m.GroupType != nil {
		n += 2 + sovCmd0X3F7(uint64(*m.GroupType))
	}
	if m.DwRequestId != nil {
		n += 2 + sovCmd0X3F7(uint64(*m.DwRequestId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Msg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WCsCmdNo != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.WCsCmdNo))
	}
	if m.Tag2 != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.Tag2))
	}
	if m.GroupCode != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.GroupCode))
	}
	if m.Cs != nil {
		l = m.Cs.Size()
		n += 1 + l + sovCmd0X3F7(uint64(l))
	}
	if m.Tag5 != nil {
		l = m.Tag5.Size()
		n += 1 + l + sovCmd0X3F7(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Cs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgSeq != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.MsgSeq))
	}
	if m.MsgRandom != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.MsgRandom))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Tag5) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tag1 != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.Tag1))
	}
	if m.Tag2 != nil {
		l = m.Tag2.Size()
		n += 1 + l + sovCmd0X3F7(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Tag5Tag2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgSeq != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.MsgSeq))
	}
	if m.Tag2 != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.Tag2))
	}
	if m.Tag3 != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.Tag3))
	}
	if m.Tag4 != nil {
		n += 1 + sovCmd0X3F7(uint64(*m.Tag4))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCmd0X3F7(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCmd0X3F7(x uint64) (n int) {
	return sovCmd0X3F7(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Targer) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: targer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: targer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WCsCmdNo", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WCsCmdNo = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupSub", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GroupSub == nil {
				m.GroupSub = &Info{}
			}
			if err := m.GroupSub.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipCmd0X3F7(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Info) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Info: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Info: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubCmd", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SubCmd = &v
		case 51:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupType", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GroupType = &v
			hasFields[0] |= uint64(0x00000001)
		case 52:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DwRequestId", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DwRequestId = &v
		default:
			iNdEx = preIndex
			skippy, err := skipCmd0X3F7(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Msg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: msg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: msg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WCsCmdNo", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WCsCmdNo = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag2", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag2 = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupCode", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GroupCode = &v
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cs == nil {
				m.Cs = &Cs{}
			}
			if err := m.Cs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag5", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tag5 == nil {
				m.Tag5 = &Tag5{}
			}
			if err := m.Tag5.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000010)
		default:
			iNdEx = preIndex
			skippy, err := skipCmd0X3F7(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Cs) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgSeq", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MsgSeq = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgRandom", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MsgRandom = &v
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipCmd0X3F7(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tag5) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: tag5: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: tag5: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag1", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag1 = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tag2 == nil {
				m.Tag2 = &Tag5Tag2{}
			}
			if err := m.Tag2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipCmd0X3F7(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tag5Tag2) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: tag5_tag2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: tag5_tag2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgSeq", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MsgSeq = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag2", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag2 = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag3", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag3 = &v
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag4", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tag4 = &v
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipCmd0X3F7(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCmd0X3F7
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCmd0X3F7(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCmd0X3F7
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmd0X3F7
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCmd0X3F7
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCmd0X3F7
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCmd0X3F7
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCmd0X3F7        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCmd0X3F7          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCmd0X3F7 = fmt.Errorf("proto: unexpected end of group")
)
